// Code generated by go-swagger; DO NOT EDIT.

package read_items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"LostAndFound/models"
)

// GetItemByIDOKCode is the HTTP code returned for type GetItemByIDOK
const GetItemByIDOKCode int = 200

/*GetItemByIDOK Item get

swagger:response getItemByIdOK
*/
type GetItemByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Item `json:"body,omitempty"`
}

// NewGetItemByIDOK creates GetItemByIDOK with default headers values
func NewGetItemByIDOK() *GetItemByIDOK {

	return &GetItemByIDOK{}
}

// WithPayload adds the payload to the get item by Id o k response
func (o *GetItemByIDOK) WithPayload(payload *models.Item) *GetItemByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get item by Id o k response
func (o *GetItemByIDOK) SetPayload(payload *models.Item) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetItemByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetItemByIDBadRequestCode is the HTTP code returned for type GetItemByIDBadRequest
const GetItemByIDBadRequestCode int = 400

/*GetItemByIDBadRequest Bad Request

swagger:response getItemByIdBadRequest
*/
type GetItemByIDBadRequest struct {
}

// NewGetItemByIDBadRequest creates GetItemByIDBadRequest with default headers values
func NewGetItemByIDBadRequest() *GetItemByIDBadRequest {

	return &GetItemByIDBadRequest{}
}

// WriteResponse to the client
func (o *GetItemByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetItemByIDNotFoundCode is the HTTP code returned for type GetItemByIDNotFound
const GetItemByIDNotFoundCode int = 404

/*GetItemByIDNotFound Item Not Found

swagger:response getItemByIdNotFound
*/
type GetItemByIDNotFound struct {
}

// NewGetItemByIDNotFound creates GetItemByIDNotFound with default headers values
func NewGetItemByIDNotFound() *GetItemByIDNotFound {

	return &GetItemByIDNotFound{}
}

// WriteResponse to the client
func (o *GetItemByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
