// Code generated by go-swagger; DO NOT EDIT.

package read_items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"LostAndFound/models"
)

// ListItemOKCode is the HTTP code returned for type ListItemOK
const ListItemOKCode int = 200

/*ListItemOK Items list

swagger:response listItemOK
*/
type ListItemOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Item `json:"body,omitempty"`
}

// NewListItemOK creates ListItemOK with default headers values
func NewListItemOK() *ListItemOK {

	return &ListItemOK{}
}

// WithPayload adds the payload to the list item o k response
func (o *ListItemOK) WithPayload(payload []*models.Item) *ListItemOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list item o k response
func (o *ListItemOK) SetPayload(payload []*models.Item) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListItemOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Item, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
