// Code generated by go-swagger; DO NOT EDIT.

package read_items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListItemHandlerFunc turns a function with the right signature into a list item handler
type ListItemHandlerFunc func(ListItemParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListItemHandlerFunc) Handle(params ListItemParams) middleware.Responder {
	return fn(params)
}

// ListItemHandler interface for that can handle valid list item params
type ListItemHandler interface {
	Handle(ListItemParams) middleware.Responder
}

// NewListItem creates a new http.Handler for the list item operation
func NewListItem(ctx *middleware.Context, handler ListItemHandler) *ListItem {
	return &ListItem{Context: ctx, Handler: handler}
}

/* ListItem swagger:route GET /items Read items listItem

ListItem list item API

*/
type ListItem struct {
	Context *middleware.Context
	Handler ListItemHandler
}

func (o *ListItem) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListItemParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
