// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Lost and Found
//
//  Schemes:
//    http
//  Host: localhost:8080
//  BasePath: /api
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
