// Code generated by go-swagger; DO NOT EDIT.

package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"LostAndFound/models"
)

// CreateItemCreatedCode is the HTTP code returned for type CreateItemCreated
const CreateItemCreatedCode int = 201

/*CreateItemCreated Item Created

swagger:response createItemCreated
*/
type CreateItemCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Item `json:"body,omitempty"`
}

// NewCreateItemCreated creates CreateItemCreated with default headers values
func NewCreateItemCreated() *CreateItemCreated {

	return &CreateItemCreated{}
}

// WithPayload adds the payload to the create item created response
func (o *CreateItemCreated) WithPayload(payload *models.Item) *CreateItemCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create item created response
func (o *CreateItemCreated) SetPayload(payload *models.Item) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateItemCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateItemBadRequestCode is the HTTP code returned for type CreateItemBadRequest
const CreateItemBadRequestCode int = 400

/*CreateItemBadRequest Bad Request

swagger:response createItemBadRequest
*/
type CreateItemBadRequest struct {
}

// NewCreateItemBadRequest creates CreateItemBadRequest with default headers values
func NewCreateItemBadRequest() *CreateItemBadRequest {

	return &CreateItemBadRequest{}
}

// WriteResponse to the client
func (o *CreateItemBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
